package io.github.pocketfly.app.ui.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBack
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import io.github.pocketfly.app.ui.components.SectionHeader

@Composable
fun AboutScreen(onBack: () -> Unit) {
    Column(
        Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(horizontal = 20.dp),
    ) {
        Row(
            Modifier
                .fillMaxWidth()
                .padding(horizontal = 0.dp, vertical = 4.dp),
        ) {
            IconButton(onClick = onBack) {
                Icon(Icons.AutoMirrored.Outlined.ArrowBack, contentDescription = "Back")
            }
            Text("About", style = MaterialTheme.typography.titleMedium, modifier = Modifier.padding(top = 12.dp))
        }

        Text("PocketFly", style = MaterialTheme.typography.headlineLarge, fontWeight = FontWeight.Bold)
        Text(
            "Mobile Drosophila CNS Sandbox",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.primary,
        )
        Text(
            "A fruit fly brain in your pocket.",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Spacer(Modifier.height(8.dp))
        Text("Version 0.1.0", style = MaterialTheme.typography.labelMedium)

        SectionHeader("What this is")
        Text(
            "PocketFly runs a simplified neural simulation over connectome " +
                "structure, locally on your phone, and connects it to small " +
                "interactive worlds: sensory in, motor out, closed loop.",
            style = MaterialTheme.typography.bodyMedium,
        )

        SectionHeader("Scientific disclaimer")
        Card(
            colors = CardDefaults.cardColors(
                containerColor = MaterialTheme.colorScheme.secondary.copy(alpha = 0.10f),
            ),
            shape = RoundedCornerShape(14.dp),
        ) {
            Text(
                "This is a connectome-based simplified simulation, not a " +
                    "complete biophysical fruit fly brain. Connectome wiring " +
                    "is not a mind: the dynamics are simplified integrate-and-" +
                    "fire parameters, the sensory encoding and action decoding " +
                    "are artificial. Behavior you see comes from structure " +
                    "plus hand-built decoders. Do not interpret game behavior " +
                    "as real fruit fly cognition.",
                Modifier.padding(14.dp),
                style = MaterialTheme.typography.bodySmall,
            )
        }

        SectionHeader("Data attribution")
        Text(
            "The bundled Sample Brain is synthetic, generated by PocketFly " +
                "tools for development, CI and demos - it is not biological " +
                "data. Imported brain packages (e.g. converted from the " +
                "public Drosophila MaleCNS connectome) remain the property " +
                "of their authors and are governed by the original dataset " +
                "license. See docs/connectome-format.md and the attribution " +
                "field in each package manifest.",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )

        SectionHeader("Project")
        Text(
            "Source code is released under the MIT license. Documentation, " +
                "issues and releases live in the GitHub repository " +
                "pocketfly.",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        TextButton(onClick = onBack) { Text("Back") }
        Spacer(Modifier.height(28.dp))
    }
}
